on: [push]

env:
  REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}

jobs:
  build:
    name: Build/test and push
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      # - name: Testing
      #   run: |
      #     npm install
      #     npm run lint
      #     npm run test
      - name: Bump Version (Patch)
        #if: github.event.pull_request.head.repo.full_name == github.repository && github.ref == 'refs/heads/master'
        run: ./scripts/bump-version.sh
      - name: Build production
        #if: github.event.pull_request.head.repo.full_name == github.repository && github.ref == 'refs/heads/master'
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $REGISTRY_DOMAIN
          PACKAGE_VERSION=$(grep version package.json | cut -c 15- | rev | cut -c 3- | rev)
          docker build . --build-arg PACKAGE_VERSION=$PACKAGE_VERSION --build-arg NODE_ENV=production --target production-stage -t $REGISTRY_DOMAIN/chrisleekr/nodejs-image-optimisation:latest -t $REGISTRY_DOMAIN/chrisleekr/nodejs-image-optimisation:$PACKAGE_VERSION
          docker push $REGISTRY_DOMAIN/chrisleekr/nodejs-image-optimisation:$PACKAGE_VERSION
          docker push $REGISTRY_DOMAIN/chrisleekr/nodejs-image-optimisation:latest
