on: [push]

env:
  REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}

jobs:
  build:
    name: Build/test and push
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      # - name: Testing
      #   run: |
      #     npm install
      #     npm run lint
      #     npm run test
      - name: Bump Version (Patch)
        # if: github.ref == 'refs/heads/master'
        run: |
          echo $GIT_CI_EMAIL
          echo $GIT_CI_NAME
          npm version patch -m "Update version to %s [skip ci]"
          git push https://$GIT_CI_USERNAME:$GIT_CI_PASSWORD@$GIT_REPO_DOMAIN/chrisleekr/nodejs-image-optimisation.git HEAD:$GITHUB_REF
      - name: docker hub login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $REGISTRY_DOMAIN
      - name: Build production
        if: github.ref == 'refs/heads/master'
        run: |
          PACKAGE_VERSION=$(grep version package.json | cut -c 15- | rev | cut -c 3- | rev)
          docker build . --build-arg PACKAGE_VERSION=$PACKAGE_VERSION --build-arg NODE_ENV=production --target production-stage -t $REGISTRY_DOMAIN/chrisleekr/nodejs-image-optimisation:latest -t $REGISTRY_DOMAIN/chrisleekr/nodejs-image-optimisation:$PACKAGE_VERSION
          docker push $REGISTRY_DOMAIN/chrisleekr/nodejs-image-optimisation:$PACKAGE_VERSION
          docker push $REGISTRY_DOMAIN/chrisleekr/nodejs-image-optimisation:latest
